services:
  ollama:
    image: ollama/ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - "ollama:/root/.ollama"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  open-webui:
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "${OPEN_WEBUI_PORT}:8080"
    volumes:
      - "open-webui:/app/backend/data"
    depends_on:
      - "ollama"
    restart: always
volumes:
  ollama:
  open-webui:
